variables:
  HELM_VERSION: 2.9.1

image: docker:latest

services:
  - docker:dind

before_script:
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

build-image:
  stage: build
  script:
   - docker build --build-arg helm_version=$HELM_VERSION -t $DOCKER_USER/docker-helm:$HELM_VERSION .
   - docker push $DOCKER_USER/helm:$HELM_VERSION
