variables:
  HELM_VERSION: $CI_COMMIT_TAG
  IMAGE_NAME: docker-helm

image: docker:latest

services:
  - docker:dind

before_script:
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

build-image:
  stage: build
  script:
   - docker build --build-arg helm_version=$HELM_VERSION -t $DOCKER_USER/$IMAGE_NAME:$HELM_VERSION .
   - docker push $DOCKER_USER/$IMAGE_NAME:$HELM_VERSION
  only:
    - tags